arb-dir: lib/src/l10n
template-arb-file: intl_de.arb
output-dir: lib/src/l10n/generated
output-localization-file: app_localizations.dart
nullable-getter: false
untranslated-messages-file: untranslated_messages.json
