# Check https://dart-lang.github.io/linter/lints/ for lint rules documentation
# Update from http://dart-lang.github.io/linter/lints/options/options.html

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
    undefined_prefixed_name: error
  language:
    strict-inference: true
    strict-raw-types: true

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - constant_identifier_names: false